---
- name: SetUp Kubernetes
  hosts: master
  become: yes
  vars_files:
    - vars/default.yml
  tasks:
  - name: install kubernetes master
    shell: |
           kubeadm init --apiserver-cert-extra-sans={{ ansible_host }} --apiserver-advertise-address=0.0.0.0 \
           --control-plane-endpoint={{ ansible_host }} --pod-network-cidr=10.244.0.0/16>>out_data.txt
    args:
      chdir: $HOME
      creates: out_data.txt

  - name: create .kube directory
    become: yes
    become_user: ubuntu
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755

  - name: copy admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ubuntu/.kube/config
      remote_src: yes
      owner: ubuntu

  - name: Download calico file
    become_user: ubuntu
    get_url:
      url: https://docs.projectcalico.org/manifests/calico.yaml
      dest: $HOME/calico.yaml
      owner: ubuntu

  - name: change string whith CALICO_IPV4POOL_CIDR
    become_user: ubuntu
    replace:
      path: $HOME/calico.yaml
      regexp: "([ ]*)(# )(-[ ]*name:[ ]*CALICO_IPV4POOL_CIDR)"
      replace: '\1\3\n\1  value: "10.244.0.0/16"'

  - name: set PODs network
    become_user: ubuntu
    shell: kubectl apply -f $HOME/calico.yaml >> calico_setup.txt
    args:
      chdir: $HOME
      creates: calico_setup.txt
