---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smongo-gce-pd-storage
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: mongo-pv
